spring:
  datasource:
    url: jdbc:postgresql://myappserver-postgresql.postgres.database.azure.com:5432/postgres
    username: omri
    password: stavCh7052!
    hikari:
      max-lifetime: 600000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8100